version: "2"

services:
  web:
    build: .
    command: npm run debug
    volumes:
      - ./.build:/server/.build
    env_file:
      - ${OneDrive}\Projects\sns-lambda\.env.dev
    ports:
      - "3000:3000"
      - "5858:5858"