service: sns-publisher

provider:
  name: aws
  runtime: nodejs6.10
  region: ${env:AWS_REGION}

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  defaultConfigType: 'cloud'
  webpack: './webpack/config.${env:WEBPACK_CONFIG_TYPE, self:custom.defaultConfigType}.js'
  webpackIncludeModules: true
  serverless-offline:
    port: '${env:VIRTUAL_PORT}'
    host: '0.0.0.0'
    location: '.webpack'

functions:
  publishSnsEvent:
    handler: handler.publishSnsEventHandler

    events:
      - http:
          path: publish/{event}
          method: post
          cors: true